#!/bin/sh
# Generates Linux route files that send VK networks to the loopback interface.

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/blacklists_updater_common.subr"

# Output directory and files
ROUTES_OUTPUT_DIR="${SCRIPT_DIR}/blacklists_route"
ROUTES_V4_FILE="${ROUTES_OUTPUT_DIR}/blacklist-vk-v4.routes"
ROUTES_V6_FILE="${ROUTES_OUTPUT_DIR}/blacklist-vk-v6.routes"

mkdir -p "${ROUTES_OUTPUT_DIR}" "${BLACKLISTS_DIR}"

echo "Generating VK route blacklists..."

build_vk_name_blacklists

# generate_routes INPUT OUTPUT TITLE ROUTE_FORMAT
generate_routes() {
    tmp="$(make_tmp)"
    {
        cat << EOF
# Linux routes for VK networks ($3)
# Auto-generated by $(basename "$0")
# Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# Apply:
#   sudo sh $(basename "$2")
#

EOF
        awk -v fmt="$4" 'NF { printf fmt, $1 }' "$1"
    } > "${tmp}"
    publish_file "${tmp}" "$2"
    echo "✓ Generated: $2 (entries: $(count_lines "$1"))"
}

# IPv4: route VK prefixes to loopback via 127.0.0.1; IPv6: via ::1.
generate_routes "${BLACKLIST_VK_V4_FILE}" "${ROUTES_V4_FILE}" "IPv4" 'ip route replace %s via 127.0.0.1 dev lo onlink\n'
generate_routes "${BLACKLIST_VK_V6_FILE}" "${ROUTES_V6_FILE}" "IPv6" 'ip -6 route replace %s via ::1 dev lo\n'

echo ""
echo "Examples:"
echo "  sudo sh ${ROUTES_V4_FILE}"
echo "  sudo sh ${ROUTES_V6_FILE}"
