#!/usr/bin/env python3
"""
generate_nft_blacklist.py
Reads prefixes from a file or stdin, aggregates them and writes nftables config.
Uses named sets for efficient blacklist management.

The generated file can be loaded again and again: each set is declared, flushed
and refilled inside a single atomic `nft -f` transaction, so prefixes removed
from the list get unblocked and merged/grown prefixes never clash with old ones.

Usage:
  git clone https://github.com/TripleA150/RU-Blacklist.git
  generate_nft_blacklist.py ./RU-Blacklist/blacklists/blacklist.txt nft_bl.conf
  generate_nft_blacklist.py --family 4 ./RU-Blacklist/blacklists/blacklist-v4.txt nft_bl_v4.conf
  sudo nft -f nft_bl.conf
"""

import argparse
import sys
from datetime import datetime, timezone
from ipaddress import collapse_addresses, ip_network
from pathlib import Path

PROFILES = {
    "vm_input": {
        "sets": {"4": "blacklist_v4", "6": "blacklist_v6"},
        "title": "VM protection from incoming blacklist sources",
        "chain": "sudo nft add chain inet filter input '{ type filter hook input priority 0; policy accept; }'",
        "rules": {
            "4": "sudo nft add rule inet filter input ip saddr @blacklist_v4 counter reject",
            "6": "sudo nft add rule inet filter input ip6 saddr @blacklist_v6 counter reject",
        },
    },
    "vk_forward": {
        "sets": {"4": "blacklist_vk_v4", "6": "blacklist_vk_v6"},
        "title": "VK egress blocking for VPN clients via NAT/FORWARD",
        "chain": "sudo nft add chain inet filter forward '{ type filter hook forward priority 0; policy accept; }'",
        "rules": {
            "4": 'sudo nft add rule inet filter forward iifname "<VPN_IFACE>" ip daddr @blacklist_vk_v4 counter reject',
            "6": 'sudo nft add rule inet filter forward iifname "<VPN_IFACE>" ip6 daddr @blacklist_vk_v6 counter reject',
        },
    },
}
SET_TYPES = {"4": "ipv4_addr", "6": "ipv6_addr"}
FAMILIES = {"4": ("4",), "6": ("6",), "both": ("4", "6")}


def read_lines(path_or_dash):
    if path_or_dash == "-":
        return [ln.rstrip("\n") for ln in sys.stdin]
    p = Path(path_or_dash)
    if not p.exists():
        raise FileNotFoundError(f"Input file not found: {path_or_dash}")
    return p.read_text(encoding="utf-8").splitlines()


def aggregate_prefixes(lines):
    v4, v6, invalid = [], [], []
    for lineno, ln in enumerate(lines, start=1):
        s = ln.split("#", 1)[0].strip()
        if not s:
            continue
        try:
            net = ip_network(s, strict=False)
        except ValueError as e:
            invalid.append((lineno, s, str(e)))
            continue
        (v4 if net.version == 4 else v6).append(net)
    return list(collapse_addresses(v4)), list(collapse_addresses(v6)), invalid


def detect_profile(source):
    return "vk_forward" if "vk" in Path(source).name.lower() else "vm_input"


def detect_family(source):
    stem = Path(source).stem.lower()
    if stem.endswith("-v4"):
        return "4"
    if stem.endswith("-v6"):
        return "6"
    return "both"


def _render(net):
    return net.with_prefixlen if hasattr(net, "with_prefixlen") else str(net)


def _set_block(name, set_type, elements):
    lines = [
        "table inet filter {",
        f"    set {name} {{",
        f"        type {set_type}",
        "        flags interval",
    ]
    if elements:
        lines.append("        elements = {")
        lines.extend(f"            {_render(net)}{',' if i < len(elements) - 1 else ''}" for i, net in enumerate(elements))
        lines.append("        }")
    lines += ["    }", "}"]
    return lines


def make_nft_config(agg_v4, agg_v6, comment=None, usage_profile="vm_input", family="both"):
    profile = PROFILES[usage_profile]
    versions = FAMILIES[family]
    elements = {"4": agg_v4, "6": agg_v6}

    lines = ["# Autogenerated nftables blacklist"]
    lines.append(f"# Generated: {datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z')}")
    if comment:
        lines.append(f"# {comment}")
    lines.append(f"# IPv4: {len(agg_v4)}, IPv6: {len(agg_v6)}")
    lines.append("#")
    lines.append("# Usage:")
    lines.append("#   sudo nft -f <this-file>")
    lines.append(f"#   # {profile['title']}")
    lines.append(f"#   {profile['chain']}")
    lines.extend(f"#   {profile['rules'][v]}" for v in versions)
    lines.append("#")
    lines.append("# Reloading is safe: the sets are flushed and refilled in one atomic transaction.")
    lines.append("")

    # 1. Make sure the table and sets exist (no-op if they already do).
    for v in versions:
        lines += _set_block(profile["sets"][v], SET_TYPES[v], [])
    # 2. Drop old elements, 3. add the current ones. nft -f applies all of it atomically.
    for v in versions:
        lines.append(f"flush set inet filter {profile['sets'][v]}")
    lines.append("")
    for v in versions:
        lines += _set_block(profile["sets"][v], SET_TYPES[v], elements[v])
        lines.append("")

    return "\n".join(lines)


def write_output(outpath, content):
    if outpath == "-":
        print(content)
        return
    p = Path(outpath)
    p.write_text(content, encoding="utf-8")
    p.chmod(0o644)


def build_parser():
    parser = argparse.ArgumentParser(description="Generate a reload-safe nftables blacklist from a list of prefixes.")
    parser.add_argument("input", help="Input file with one prefix per line ('-' for STDIN).")
    parser.add_argument("output", help="Output nftables file ('-' for STDOUT).")
    parser.add_argument("--profile", choices=["auto", *PROFILES], default="auto",
                        help="Set names/usage example; 'auto' picks vk_forward if the input name contains 'vk'.")
    parser.add_argument("--family", choices=["auto", *FAMILIES], default="auto",
                        help="Which sets to emit; 'auto' uses the -v4/-v6 suffix of the input name.")
    parser.add_argument("-q", "--quiet", action="store_true", help="Only print errors.")
    parser.add_argument("-v", "--verbose", action="store_true", help="Print every aggregated prefix.")
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    log = (lambda *a: None) if args.quiet else (lambda *a: print(*a, file=sys.stderr))

    try:
        lines = read_lines(args.input)
    except OSError as e:
        print(f"ERROR reading input: {e}", file=sys.stderr)
        return 3

    agg_v4, agg_v6, invalid = aggregate_prefixes(lines)
    for ln, txt, err in invalid:
        print(f"WARNING: line {ln}: '{txt}' --> {err}", file=sys.stderr)
    if not agg_v4 and not agg_v6:
        print("WARNING: input contains no prefixes; writing empty sets.", file=sys.stderr)

    source = "stdin" if args.input == "-" else args.input
    profile = detect_profile(source) if args.profile == "auto" else args.profile
    family = detect_family(source) if args.family == "auto" else args.family
    if family == "4" and agg_v6:
        log(f"Ignoring {len(agg_v6)} IPv6 prefixes (--family 4)")
    if family == "6" and agg_v4:
        log(f"Ignoring {len(agg_v4)} IPv4 prefixes (--family 6)")
    agg_v4 = agg_v4 if family != "6" else []
    agg_v6 = agg_v6 if family != "4" else []

    log(f"Aggregated IPv4 prefixes: {len(agg_v4)}, IPv6 prefixes: {len(agg_v6)}")
    if args.verbose:
        for n in agg_v4 + agg_v6:
            log(f"  {n}")

    nft_conf = make_nft_config(agg_v4, agg_v6, comment=f"Source: {Path(source).name}",
                               usage_profile=profile, family=family)
    try:
        write_output(args.output, nft_conf)
    except OSError as e:
        print(f"ERROR writing output: {e}", file=sys.stderr)
        return 4

    if args.output != "-":
        log(f"Wrote nft config to: {args.output}")
        log("Load with: sudo nft -f <output.conf>")
    return 0


if __name__ == "__main__":
    sys.exit(main())
