[project]
name = "ru-blacklist"
description = "Blacklists generator of subnets of Russian government agencies"
requires-python = ">=3.10"
version = "0"

[tool.ruff]
line-length = 140
target-version = "py310"
extend-exclude = ["config", "data", "output"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "UP", "BLE", "EXE"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "-ra"
